image: golang:1.12.2

stages:
  - build
  - lint
  - test
  - report

build-api:
  stage: build
  script:
    - go build cmd/server/main.go
    - parcel build ui/index.html

build-ui:
  stage: build
  image: node:14
  script:
    - cd ui
    - npm install
    - npx run parcel build index.html

lint-api:
  stage: lint
  script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s latest
    - ./bin/golangci-lint run ./...

test:
  stage: test
  script:
    - go test -v -cover -covermode=count -coverprofile=.coverage.out ./...
    - "go tool cover -func .coverage.out | grep total: | awk '{printf \"total code coverage: %s\", $3}'"
    - go tool cover -html=.coverage.out -o coverage.html
  coverage: '/total code coverage: \d+\.\d+/'
  artifacts:
    paths:
      - coverage.html

pages:
  stage: report
  dependencies:
    - test
  script:
    - mkdir -p public/
    - mv coverage.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
