image: golang:1.12.2

stages:
  - build
  - lint
  - test
  - report

build:
  stage: build
  script:
    - go build cmd/server/main.go

lint:
  stage: lint
  script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s latest
    - ./bin/golangci-lint run ./...

test:
  stage: test
  script:
    # - go test -v ./...
    go test -v ./bolt

coverage:
  stage: test
  script:
    - go test -cover -covermode=count -coverprofile=.coverage.out ./bolt
    - go tool cover -html=.coverage.out -o coverage.html
  coverage: '/coverage: \d+\.\d+/'
  artifacts:
    paths:
      - coverage.html

pages:
  stage: report
  dependencies:
    - coverage
  script:
    - mkdir -p public/
    - mv coverage.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 30 days
