run:
  deadline: 1m

issues:
  exclude-use-default: false
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - golint
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - goconst
    - typecheck
    - gocyclo
    - gosec
