name: Svelte

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

defaults:
  run:
    shell: bash
    working-directory: ui

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Install Deps
      run: npm install

    - name: Build
      run: npm run build

    - name: check
      run: npm run validate

